"use client";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { json, useAction, ErrorMessage, dateLabel } from "./client";
import { Requests } from "./requests";
type Shift = { id: string; date: string; title: string | null; shiftFrom: string; shiftTo: string; occupiedCount: number; maxEmployees: number; description: string | null; branch: { name: string; address: string | null; meetingPoint: string | null; notes: string | null } | null; bookings: { userId: string; confirmedAt: string | null; user: { firstName: string; lastName: string } }[] };
type Dashboard = { manager: boolean; firstName: string; userId: string; today: string; own: Shift[]; todayShifts: Shift[]; open: Shift[]; unconfirmed: number; unread: number; absences: { id: string; status: string; dateFrom: string; dateTo: string; user: { firstName: string; lastName: string }; category: { name: string } }[]; reports: { employees: { userId: string; firstName: string; lastName: string; totalMinutes: number; plannedMinutes: number; targetMinutes: number; deviationMinutes: number }[] } };
export function Dashboard() {
  const query = useQuery({ queryKey: ["dashboard"], queryFn: () => json<Dashboard>("/api/dashboard"), refetchInterval: 30000 });
  const action = useAction(), data = query.data;
  if (query.error) return <ErrorMessage error={query.error} />;
  if (!data) return <p>Übersicht wird geladen …</p>;
  const hours = (v: number) => (v / 60).toLocaleString("de-DE", { maximumFractionDigits: 2 }) + " h";
  function shiftCard(s: Shift, open = false) {
    const own = s.bookings.find(b => b.userId === data!.userId);
    return <article key={s.id} className="border-t py-4 space-y-2"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{dateLabel(s.date)} · {s.shiftFrom}–{s.shiftTo}</strong><Badge variant="secondary">{s.occupiedCount}/{s.maxEmployees} besetzt</Badge></div><p>{s.title || "Schicht"}{s.branch ? " · " + s.branch.name : ""}</p>{s.branch && <p className="text-sm text-muted-foreground">{s.branch.address}{s.branch.meetingPoint ? " · Treffpunkt: " + s.branch.meetingPoint : ""}</p>}{(s.description || s.branch?.notes) && <p className="text-sm">{[s.description, s.branch?.notes].filter(Boolean).join(" · ")}</p>}
      {data?.manager ? <p className="text-sm">{s.bookings.map(b => b.user.firstName + " " + b.user.lastName + (b.confirmedAt ? " ✓" : " · unbestätigt")).join(", ") || "Noch nicht besetzt"}</p> : <div className="flex flex-wrap gap-2">{own && <><Button size="sm" variant={own.confirmedAt ? "outline" : "default"} disabled={!!own.confirmedAt || action.isPending} onClick={() => action.mutate({ url: "/api/bookings", method: "PATCH", data: { shiftId: s.id } })}>{own.confirmedAt ? "Bestätigt" : "Schicht bestätigen"}</Button><Button size="sm" variant="outline" disabled={action.isPending} onClick={() => action.mutate({ url: "/api/mod-requests", data: { shiftId: s.id, kind: "SWAP" } })}>Zum Tausch anbieten</Button></>}{open && !own && <Button size="sm" disabled={action.isPending} onClick={() => action.mutate({ url: "/api/mod-requests", data: { shiftId: s.id } })}>Übernahme anfragen</Button>}</div>}
      <Link className="text-sm text-primary underline" href={"/portal/inbox?shiftId=" + s.id}>Nachricht zur Schicht</Link>
    </article>;
  }
  return <div className="space-y-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-muted-foreground">{dateLabel(data.today)}</p><h1>Guten Tag, {data.firstName}</h1><p className="mt-2 text-muted-foreground">{data.manager ? "Dein Überblick für die Einsatzplanung." : "Dein Dienstplan und alles, was heute wichtig ist."}</p></div><Button asChild><Link href="/schedule/flexible">Dienstplan öffnen</Link></Button></div>
    <div className="flex flex-wrap gap-x-8 gap-y-4 border-y py-4">{[[data.todayShifts.length, "Schichten heute"], [data.open.length, "Offene Schichten"], [data.unconfirmed, "Bestätigungen fehlen"], [data.unread, "Neue Nachrichten"]].map(([n,label]) => <div key={label}><span className="text-2xl font-semibold text-primary">{n}</span><p className="text-sm text-muted-foreground">{label}</p></div>)}</div>
    <div className="grid gap-6 lg:grid-cols-[1.4fr_1fr]"><Card className="p-5"><h2>{data.manager ? "Heutige Schichten" : "Deine nächste Schicht"}</h2>{data.manager ? data.todayShifts.length ? data.todayShifts.map(s => shiftCard(s)) : <p>Heute sind keine weiteren Schichten geplant.</p> : data.own.length ? shiftCard(data.own[0]) : <p>Für dich ist noch keine kommende Schicht veröffentlicht.</p>}{!data.manager && data.todayShifts.filter(s => s.id !== data.own[0]?.id).map(s => shiftCard(s))}</Card><Card className="p-5"><h2>{data.manager ? "Aktuelle Abwesenheiten" : "Deine Abwesenheiten"}</h2>{data.absences.length ? data.absences.map(a => <div className="border-t py-3" key={a.id}><p>{a.user.firstName} {a.user.lastName} · {a.category.name}</p><p className="text-sm text-muted-foreground">{dateLabel(a.dateFrom)}–{dateLabel(a.dateTo)} · {a.status === "PENDING" ? "Zur Freigabe" : "Genehmigt"}</p></div>) : <p className="text-sm text-muted-foreground">Keine aktuellen Abwesenheiten.</p>}<Link className="text-sm text-primary underline" href="/employees/absences">Abwesenheiten und Verfügbarkeit</Link></Card></div>
    {!data.manager && data.own.length > 1 && <details><summary className="cursor-pointer font-semibold">Weitere eigene Schichten ({data.own.length - 1})</summary>{data.own.slice(1).map(s => shiftCard(s))}</details>}
    <section><h2 className="mb-4">Offene Schichten</h2><Card className="p-5">{data.open.length ? data.open.slice(0,20).map(s => shiftCard(s, true)) : <p>Aktuell keine passenden offenen Schichten.</p>}</Card></section>
    <Requests manager={data.manager} userId={data.userId} />
    <section><h2 className="mb-4">{data.manager ? "Stunden und Abweichungen im Monat" : "Deine Monatsstunden"}</h2><div className="overflow-x-auto rounded-md border bg-card"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Mitarbeiter</th><th className="p-3">Soll</th><th className="p-3">Geplant</th><th className="p-3">Erfasst</th><th className="p-3">Ist − Plan</th></tr></thead><tbody>{data.reports.employees.map(e => <tr key={e.userId} className="border-b"><td className="p-3">{e.firstName} {e.lastName}</td><td className="p-3">{hours(e.targetMinutes)}</td><td className="p-3">{hours(e.plannedMinutes)}</td><td className="p-3">{hours(e.totalMinutes)}</td><td className="p-3">{hours(e.deviationMinutes)}</td></tr>)}</tbody></table></div><p className="mt-2 text-xs text-muted-foreground">Soll = Wochenstunden / 5 × Montag–Freitag im Monat. Ist/Plan vergleicht den gesamten Monat einschließlich künftiger Schichten.</p><div className="mt-3 flex flex-wrap gap-4"><Link href="/time" className="text-primary underline">Zeiterfassung öffnen</Link><a className="text-primary underline" href="/api/reporting/export">Stunden als CSV exportieren</a><Link className="text-primary underline" href="/portal/inbox">Nachrichten ({data.unread})</Link></div></section>
  </div>;
}
