"use client";
import { useQuery } from "@tanstack/react-query";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { json, useAction, ErrorMessage, dateLabel } from "./client";
type RequestRow = { id: string; kind: string; state: string; userId: string; targetUserId: string | null; note: string | null; user: { firstName: string; lastName: string }; shift: { title: string | null; shiftFrom: string; shiftTo: string } };
type Correction = { id: string; status: string; reason: string; before: Record<string, unknown>; proposed: Record<string, unknown>; record: { date: string; user: { firstName: string; lastName: string } } };
const labels: Record<string,string> = { OPEN: "Offen", ACCEPTED: "Genehmigt", DECLINED: "Abgelehnt", PENDING: "Zur Freigabe", APPROVED: "Genehmigt" };
const fieldLabels: Record<string,string> = { date: "Datum", timeFrom: "Beginn", timeTo: "Ende", durationHours: "Stunden", durationMinutes: "Minuten", breakMinutes: "Pause (Min.)", comment: "Kommentar", categoryId: "Kategorie" };
export function Requests({ manager, userId }: { manager: boolean; userId: string }) {
  const requests = useQuery({ queryKey: ["requests"], queryFn: () => json<{ requests: RequestRow[] }>("/api/mod-requests") });
  const corrections = useQuery({ queryKey: ["corrections"], queryFn: () => json<{ corrections: Correction[] }>("/api/time/corrections") });
  const action = useAction();
  return <section id="antraege" className="space-y-4"><h2 className="text-[16px] font-semibold tracking-[-0.02em]">{manager ? "Anträge bearbeiten" : "Anträge und Schichttausch"}</h2><ErrorMessage error={requests.error || corrections.error} />
    <div className="grid gap-4 lg:grid-cols-2"><Card className="p-4"><h3 className="text-[14px] font-semibold tracking-[-0.02em]">Übernahmen und Schichttausch</h3>{requests.isPending ? <p>Lädt …</p> : !requests.data?.requests.length ? <p className="text-sm text-muted-foreground">Keine Anträge vorhanden.</p> : requests.data.requests.map(r => <div key={r.id} className="space-y-2 border-t py-3"><p className="font-medium">{r.kind === "SWAP" ? "Schichttausch" : "Übernahme"} · {labels[r.state]}</p><p className="text-sm">{r.user.firstName} {r.user.lastName} · {r.shift.title || "Schicht"} · {r.shift.shiftFrom}–{r.shift.shiftTo}</p>{r.note && <p className="text-sm">{r.note}</p>}
      {r.state === "OPEN" && <div className="flex flex-wrap gap-2">{manager ? <><Button size="sm" disabled={action.isPending || (r.kind === "SWAP" && !r.targetUserId)} onClick={() => action.mutate({ url: "/api/mod-requests/" + r.id, method: "PATCH", data: { state: "ACCEPTED" } })}>Genehmigen</Button><Button size="sm" variant="outline" disabled={action.isPending} onClick={() => action.mutate({ url: "/api/mod-requests/" + r.id, method: "PATCH", data: { state: "DECLINED" } })}>Ablehnen</Button></> : r.userId !== userId && !r.targetUserId ? <Button size="sm" disabled={action.isPending} onClick={() => action.mutate({ url: "/api/mod-requests/" + r.id, method: "PATCH", data: { volunteer: true } })}>Übernahme anbieten</Button> : r.userId === userId ? <Button size="sm" variant="outline" disabled={action.isPending} onClick={() => action.mutate({ url: "/api/mod-requests/" + r.id, method: "DELETE" })}>Zurückziehen</Button> : <p className="text-sm">Deine Übernahme wartet auf Freigabe.</p>}</div>}
      {r.kind === "SWAP" && !r.targetUserId && r.state === "OPEN" && <p className="text-sm text-muted-foreground">Wartet auf eine passende Übernahme.</p>}
    </div>)}</Card>
    <Card className="p-4"><h3 className="text-[14px] font-semibold tracking-[-0.02em]">Zeitkorrekturen</h3>{corrections.isPending ? <p>Lädt …</p> : !corrections.data?.corrections.length ? <p className="text-sm text-muted-foreground">Keine Zeitkorrekturen vorhanden.</p> : corrections.data.corrections.map(c => <div key={c.id} className="space-y-2 border-t py-3"><p className="font-medium">{c.record.user.firstName} {c.record.user.lastName} · {dateLabel(c.record.date)}</p><p className="text-sm">{c.reason} · {labels[c.status]}</p><dl className="text-sm">{Object.entries(c.proposed).map(([key,value]) => <div key={key}><dt className="inline text-muted-foreground">{fieldLabels[key] || key}: </dt><dd className="inline">{String(c.before[key] ?? "–")} → {String(value ?? "–")}</dd></div>)}</dl>{manager && c.status === "PENDING" && <div className="flex gap-2"><Button size="sm" disabled={action.isPending} onClick={() => action.mutate({ url: "/api/time/corrections", method: "PATCH", data: { id: c.id, status: "APPROVED" } })}>Bestätigen</Button><Button size="sm" variant="outline" disabled={action.isPending} onClick={() => action.mutate({ url: "/api/time/corrections", method: "PATCH", data: { id: c.id, status: "DECLINED" } })}>Ablehnen</Button></div>}</div>)}</Card></div>
  </section>;
}
